# Generated by Django 5.2.14 on 2026-05-31 11:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=8)),
                ('tcmb_code', models.CharField(blank=True, help_text='TCMB forex code in today.xml (e.g. USD, EUR, GBP). Null for manual-only currencies.', max_length=8, null=True)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'platform_currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModulePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(max_length=64, unique=True)),
                ('price_per_user_monthly', models.DecimalField(decimal_places=2, help_text='TRY per active user per month for this module.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_module_price',
                'ordering': ['module_slug'],
            },
        ),
        migrations.CreateModel(
            name='PlatformBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_monthly_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('yearly_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default yearly discount % for tenants without override.', max_digits=5)),
                ('invoice_prefix', models.CharField(default='TEN', max_length=16)),
                ('default_payment_terms_days', models.PositiveSmallIntegerField(default=7)),
                ('company_name', models.CharField(default='Tenancysoft', max_length=255)),
                ('company_tax_id', models.CharField(blank=True, max_length=32)),
                ('company_address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'platform billing settings',
                'db_table': 'platform_billing_settings',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'platform_tax_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscriptionInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('user_count', models.PositiveIntegerField()),
                ('unit_price_list', models.DecimalField(blank=True, decimal_places=4, help_text='List unit price (1 user × 1 month) before discount, invoice currency.', max_digits=14, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('line_total_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_excl_tax', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'tenant_subscription_invoice_line',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField()),
                ('method', models.CharField(default='bank_transfer', max_length=64)),
                ('reference', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'tenant_subscription_payment',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_try', models.DecimalField(decimal_places=6, help_text='How many TRY for 1 unit of currency.', max_digits=18)),
                ('source', models.CharField(choices=[('tcmb', 'TCMB'), ('manual', 'Manual')], max_length=16)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='platform_billing.currency')),
            ],
            options={
                'db_table': 'platform_exchange_rate',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='platform_billing.taxtype')),
            ],
            options={
                'db_table': 'platform_tax_rate',
                'ordering': ['tax_type__code', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16)),
                ('fx_rate_to_try', models.DecimalField(decimal_places=6, help_text='TRY per 1 invoice currency unit at issue time.', max_digits=18)),
                ('subtotal_before_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal in invoice currency before billing discount.', max_digits=14, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Billing discount % snapshot applied on this invoice.', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount in invoice currency.', max_digits=14, null=True)),
                ('subtotal_excl_tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_lines', models.JSONField(default=list)),
                ('total_incl_tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_billing.currency')),
            ],
            options={
                'db_table': 'tenant_subscription_invoice',
                'ordering': ['-period_end', '-number'],
            },
        ),
    ]
