# Generated by Django 5.2.14 on 2026-05-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscriptioninvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsubscriptioninvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='platform_billing.tenantsubscriptioninvoice'),
        ),
        migrations.AddField(
            model_name='tenantsubscriptionpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='platform_billing.tenantsubscriptioninvoice'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', '-fetched_at'], name='platform_ex_currenc_e05553_idx'),
        ),
    ]
