# Generated by Django 5.2.14 on 2026-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsubscriptioninvoice',
            name='subtotal_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal in invoice currency before billing discount.', max_digits=14, null=True),
        ),
    ]
