PERMISSION_CODENAMES = [
    ("settings.read", "View settings / departments"),
    ("settings.write", "Manage settings / departments"),
    ("employees.read", "View employees"),
    ("employees.write", "Manage employees"),
    ("products.read", "View products"),
    ("products.write", "Manage products"),
    ("inventory.read", "View inventory"),
    ("inventory.write", "Manage inventory"),
    ("customers.read", "View customers"),
    ("customers.write", "Manage customers"),
    ("patients.read", "View patient records"),
    ("patients.write", "Manage patient records"),
    ("appointments.read", "View appointments"),
    ("appointments.write", "Manage appointments"),
    ("billing.read", "View billing"),
    ("billing.write", "Manage billing"),
    ("accounting.read", "View accounting"),
    ("accounting.write", "Manage accounting"),
    ("dashboard.read", "View dashboard"),
    ("audit.read", "View audit logs"),
]

ALL_MODULES = [
    "settings",
    "employees",
    "products",
    "inventory",
    "customers",
    "patients",
    "appointments",
    "billing",
    "accounting",
    "dashboard",
    "audit",
]
