# Generated by Django 5.2.15 on 2026-07-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_note', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dental_tariff',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DentalTariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.PositiveSmallIntegerField()),
                ('section_name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=512)),
                ('price_excl_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_incl_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tariff.dentaltariff')),
            ],
            options={
                'db_table': 'dental_tariff_item',
                'ordering': ['section_no', 'code'],
                'indexes': [models.Index(fields=['tariff', 'code'], name='dental_tari_tariff__7f4e3e_idx'), models.Index(fields=['tariff', 'name'], name='dental_tari_tariff__368b8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tariff', 'code'), name='dental_tariff_item_unique_code')],
            },
        ),
    ]
