# Generated by Django 5.2.14 on 2026-07-08 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_note', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dental_tariff',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DentalTariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.PositiveSmallIntegerField()),
                ('section_name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=512)),
                ('price_incl_vat', models.DecimalField(decimal_places=2, help_text='TDB reference price, VAT included (canonical). VAT-excl is derived.', max_digits=12)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tariff.dentaltariff')),
            ],
            options={
                'db_table': 'dental_tariff_item',
                'ordering': ['section_no', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantTariffItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_price_incl_vat', models.DecimalField(decimal_places=2, help_text='Clinic price, VAT included (canonical). VAT-excl is derived in UI.', max_digits=12)),
                ('floor_bumped', models.BooleanField(default=False, help_text='True when a yearly tariff update raised this price to the new floor.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_prices', to='tariff.dentaltariffitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_item_prices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_tariff_item_price',
            },
        ),
        migrations.AddIndex(
            model_name='dentaltariffitem',
            index=models.Index(fields=['tariff', 'code'], name='dental_tari_tariff__7f4e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='dentaltariffitem',
            index=models.Index(fields=['tariff', 'name'], name='dental_tari_tariff__368b8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dentaltariffitem',
            constraint=models.UniqueConstraint(fields=('tariff', 'code'), name='dental_tariff_item_unique_code'),
        ),
        migrations.AddIndex(
            model_name='tenanttariffitemprice',
            index=models.Index(fields=['tenant', 'tariff_item'], name='tenant_tari_tenant__78d625_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenanttariffitemprice',
            constraint=models.UniqueConstraint(fields=('tenant', 'tariff_item'), name='tenant_tariff_item_price_unique'),
        ),
    ]
