# Generated by Django 5.2.14 on 2026-07-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('customers', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=32)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('device_brand', models.CharField(blank=True, max_length=128)),
                ('device_model', models.CharField(blank=True, max_length=128)),
                ('device_serial', models.CharField(blank=True, max_length=128)),
                ('complaint', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('iban', 'Bank transfer')], max_length=16)),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosing', 'Diagnosing'), ('awaiting_approval', 'Awaiting approval'), ('in_repair', 'In repair'), ('ready', 'Ready for pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'service_ticket',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_ticket_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='service.serviceticket')),
            ],
            options={
                'db_table': 'service_ticket_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['tenant', 'status'], name='service_tic_tenant__cff9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['tenant', 'ticket_number'], name='service_tic_tenant__ca0f24_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['tenant', 'customer_phone'], name='service_tic_tenant__0a851e_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceticket',
            constraint=models.UniqueConstraint(fields=('tenant', 'ticket_number'), name='service_ticket_unique_number'),
        ),
    ]
