# Generated by Django 5.2.15 on 2026-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbology', models.CharField(default='EAN13', max_length=16)),
                ('qr_payload', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'barcode_assignment',
            },
        ),
        migrations.CreateModel(
            name='BarcodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_miss_action', models.CharField(choices=[('ignore', 'Ignore'), ('assign_existing', 'Assign to existing product'), ('create_wizard', 'Create product wizard')], default='create_wizard', max_length=32)),
                ('normalize_tr_scan', models.BooleanField(default=True)),
                ('qr_content_mode', models.CharField(choices=[('barcode', 'Barcode only'), ('sku', 'SKU only'), ('compact_detail', 'Compact product detail')], default='barcode', max_length=32)),
                ('qr_max_length', models.PositiveIntegerField(default=128)),
                ('ean_prefix', models.CharField(default='869', max_length=3)),
                ('auto_generate_on_create', models.BooleanField(default=False)),
                ('operation_flags', models.JSONField(default=dict)),
                ('stock_deduction_mode', models.CharField(choices=[('off', 'Off'), ('on_invoice', 'On invoice'), ('on_manual_confirm', 'Manual confirm'), ('both', 'Both')], default='both', max_length=32)),
                ('print_mode', models.CharField(choices=[('queue_only', 'Queue only'), ('immediate', 'Immediate'), ('both', 'Both')], default='both', max_length=32)),
                ('default_copies', models.PositiveIntegerField(default=1)),
                ('default_transfer_qty', models.PositiveIntegerField(default=1)),
                ('printer_model', models.CharField(default='XP-P328B', max_length=64)),
                ('printer_profile_json', models.JSONField(default=dict)),
                ('label_logo', models.ImageField(blank=True, null=True, upload_to='barcode/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'barcode_settings',
            },
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gap_mm', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('dpi', models.PositiveIntegerField(default=203)),
                ('layout_json', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('duplicate', 'Duplicate')], default='custom', max_length=16)),
                ('default_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('allowed_department_keys', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'label_template',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.JSONField(default=list)),
                ('layout_snapshot', models.JSONField(default=list)),
                ('template_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'barcode_print_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
