# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeassignment',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_assignment', to='products.product'),
        ),
        migrations.AddField(
            model_name='barcodeassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='barcodesettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_settings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='barcodesettings',
            name='default_label_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_defaults', to='barcode.labeltemplate'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_print_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='barcode.labeltemplate'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='labeltemplate',
            index=models.Index(fields=['tenant_id', 'is_active'], name='label_templ_tenant__49ff07_idx'),
        ),
        migrations.AddIndex(
            model_name='labeltemplate',
            index=models.Index(fields=['tenant_id', 'default_key'], name='label_templ_tenant__6d696c_idx'),
        ),
        migrations.AddConstraint(
            model_name='labeltemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('default_key', ''), _negated=True), fields=('tenant_id', 'default_key'), name='label_template_unique_default_key'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['tenant_id', 'status'], name='barcode_pri_tenant__b3ea09_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['tenant_id', 'created_at'], name='barcode_pri_tenant__4e1e97_idx'),
        ),
    ]
