# Generated by Django 5.2.15 on 2026-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='context_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='printjob',
            name='context_type',
            field=models.CharField(choices=[('product', 'Product'), ('service_ticket', 'Service ticket')], default='product', max_length=32),
        ),
    ]
