# Generated by Django 5.2.14 on 2026-07-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable key e.g. admin, cashier.', max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'department',
                'ordering': ['tenant_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, help_text='Refresh token id (jti) that owns this session.', max_length=255)),
                ('client', models.CharField(choices=[('web', 'Web'), ('eimza', 'e-İmza'), ('ebarcode', 'e-Barcode'), ('unknown', 'Unknown')], default='web', max_length=16)),
                ('client_version', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_session',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('login_key', models.CharField(db_index=True, editable=False, help_text='Internal unique key (tenant_id + email); login uses customer_code + email.', max_length=191, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('tckn', models.CharField(blank=True, help_text='Doctor/staff T.C. kimlik no (Medula e-Reçete).', max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, db_table='user_group', help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
