# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='user_auth_permission', help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='department_permission', related_name='departments', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, db_table='user_extra_permission', help_text="Additional permissions on top of the user's department.", related_name='users_with_extra', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'key')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'email'], name='user_tenant__421534_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='u_user_tenant_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('email',), name='u_platform_email'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['tenant', 'revoked', 'last_seen_at'], name='user_sessio_tenant__69a821_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['jti'], name='user_sessio_jti_f57633_idx'),
        ),
    ]
