# Generated by Django 5.2.14 on 2026-05-31 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOralChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaw_type', models.CharField(choices=[('permanent', 'Permanent'), ('primary', 'Primary'), ('mixed', 'Mixed')], default='permanent', max_length=16)),
                ('teeth_state', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'patient_oral_chart',
            },
        ),
        migrations.CreateModel(
            name='ProcedureCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('planning', 'Planning'), ('treatment', 'Treatment')], default='treatment', max_length=16)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_frequent', models.BooleanField(default=False)),
                ('default_tooth_condition', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'oral_procedure_catalog',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OralTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_numbers', models.JSONField(default=list)),
                ('surfaces', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('phase', models.CharField(blank=True, max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planned_at', models.DateField(blank=True, null=True)),
                ('performed_at', models.DateField(blank=True, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oral_treatments_performed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oral_treatments', to='customers.customer')),
            ],
            options={
                'db_table': 'oral_treatment',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
