# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('oral', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraltreatment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='patientoralchart',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oral_chart', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='patientoralchart',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oral_procedures', to='products.product'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='oraltreatment',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='oral.procedurecatalog'),
        ),
        migrations.AddIndex(
            model_name='procedurecatalog',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='oral_proced_tenant__5acf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='oraltreatment',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='oral_treatm_tenant__29ab20_idx'),
        ),
        migrations.AddIndex(
            model_name='oraltreatment',
            index=models.Index(fields=['tenant', 'session_date'], name='oral_treatm_tenant__6a76d0_idx'),
        ),
    ]
