# Generated by Django 5.2.14 on 2026-06-15 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_discount_amount_invoice_discount_percent_and_more'),
        ('oral', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraltreatment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oral_treatments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='oraltreatment',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
