# Generated by Django 5.2.15 on 2026-07-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral', '0002_initial'),
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecatalog',
            name='tariff_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='tariff.dentaltariffitem'),
        ),
    ]
