# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('oral', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barkod', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(blank=True, max_length=64)),
                ('strength', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, default='adet', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'drug_catalog',
                'ordering': ['name'],
                'unique_together': {('tenant', 'barkod')},
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_no', models.CharField(blank=True, max_length=32)),
                ('diagnosis_code', models.CharField(blank=True, max_length=16)),
                ('diagnosis_text', models.CharField(blank=True, max_length=255)),
                ('prescription_type', models.CharField(choices=[('normal', 'Normal'), ('kirmizi', 'Kırmızı'), ('yesil', 'Yeşil'), ('mor', 'Mor'), ('turuncu', 'Turuncu')], default='normal', max_length=16)),
                ('provision_type', models.CharField(choices=[('sgk', 'SGK'), ('ucretli', 'Ücretli'), ('yesil_kart', 'Yeşil Kart'), ('emekli', 'Emekli Sandığı')], default='sgk', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('medula_reference', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_authored', to=settings.AUTH_USER_MODEL)),
                ('oral_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='oral.oraltreatment')),
                ('patient', models.ForeignKey(limit_choices_to={'kind': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'prescription',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_barkod', models.CharField(blank=True, max_length=32)),
                ('drug_name', models.CharField(max_length=255)),
                ('box_count', models.PositiveIntegerField(default=1)),
                ('quantity_per_box', models.PositiveIntegerField(default=1)),
                ('dose', models.CharField(blank=True, max_length=64)),
                ('frequency', models.CharField(blank=True, max_length=64)),
                ('period_days', models.PositiveIntegerField(default=7)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topikal'), ('iv', 'IV'), ('im', 'IM'), ('sc', 'SC'), ('other', 'Diğer')], default='oral', max_length=16)),
                ('usage_instruction', models.CharField(blank=True, max_length=512)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prescriptions.drugcatalog')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='prescriptions.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'prescription_line',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='prescriptio_tenant__c859af_idx'),
        ),
    ]
