# Generated by Django 5.2.14 on 2026-05-22 12:41

import apps.customers.patient_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('customer', 'Customer'), ('patient', 'Patient')], default='customer', max_length=16)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, choices=[('tc', 'Turkish citizen'), ('foreign', 'Foreign national')], max_length=16)),
                ('tckn', models.CharField(blank=True, db_index=True, max_length=11)),
                ('foreign_id', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=32)),
                ('home_phone', models.CharField(blank=True, max_length=32)),
                ('work_phone', models.CharField(blank=True, max_length=32)),
                ('home_address', models.JSONField(blank=True, default=dict)),
                ('work_address', models.JSONField(blank=True, default=dict)),
                ('nvi_verified', models.BooleanField(default=False)),
                ('nvi_verified_at', models.DateTimeField(blank=True, null=True)),
                ('nvi_reference', models.CharField(blank=True, max_length=128)),
                ('photo', models.ImageField(blank=True, max_length=512, null=True, upload_to=apps.customers.patient_photo.patient_photo_upload_to)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_record',
                'ordering': ['-updated_at'],
            },
        ),
    ]
