# Generated by Django 5.2.14 on 2026-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', help_text='Default UI and API message language for this tenant.', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled_modules', models.JSONField(default=list, help_text="Module slugs this tenant can use, e.g. ['products', 'billing'].")),
                ('module_labels', models.JSONField(blank=True, default=dict, help_text='Display names keyed by module slug, e.g. {"customers": "Hastalar"}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant',
                'ordering': ['customer_code'],
            },
        ),
    ]
