# Generated by Django 5.2.14 on 2026-05-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', help_text='Default UI and API message language for this tenant.', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled_modules', models.JSONField(default=list, help_text="Module slugs this tenant can use, e.g. ['products', 'billing'].")),
                ('module_labels', models.JSONField(blank=True, default=dict, help_text='Display names keyed by module slug, e.g. {"customers": "Hastalar"}.')),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum active staff users allowed for this tenant.')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16)),
                ('yearly_discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Override platform default yearly discount; null uses global setting.', max_digits=5, null=True)),
                ('billing_anchor_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month (1-28) for billing period anchor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='platform_billing.currency')),
            ],
            options={
                'db_table': 'tenant',
                'ordering': ['customer_code'],
            },
        ),
        migrations.CreateModel(
            name='TenantModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_extra', models.BooleanField(default=False, help_text='Granted beyond the base package by platform admin.')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_module_subscription',
                'ordering': ['tenant_id', 'module_slug'],
                'unique_together': {('tenant', 'module_slug')},
            },
        ),
    ]
