# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('label_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='barcode.labeltemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('field_source', models.CharField(choices=[('CORE', 'CORE'), ('DYNAMIC', 'DYNAMIC'), ('COMPUTED', 'COMPUTED')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(default='Genel Bilgiler', max_length=128)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_detail_config',
                'ordering': ['section', 'order', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='ProductFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'TEXT'), ('TEXTAREA', 'TEXTAREA'), ('NUMBER', 'NUMBER'), ('DECIMAL', 'DECIMAL'), ('BOOLEAN', 'BOOLEAN'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('SELECT', 'SELECT'), ('MULTI_SELECT', 'MULTI_SELECT'), ('URL', 'URL'), ('EMAIL', 'EMAIL'), ('PHONE', 'PHONE'), ('MONEY', 'MONEY'), ('PERCENT', 'PERCENT'), ('FILE', 'FILE'), ('IMAGE', 'IMAGE'), ('JSON', 'JSON')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=512)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('is_sortable', models.BooleanField(default=False)),
                ('show_in_form', models.BooleanField(default=True)),
                ('show_in_list', models.BooleanField(default=False)),
                ('show_in_detail', models.BooleanField(default=True)),
                ('form_order', models.PositiveIntegerField(default=0)),
                ('list_order', models.PositiveIntegerField(default=0)),
                ('detail_order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_field_definition',
                'ordering': ['form_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProductFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.BigIntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, upload_to='product_fields/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productfielddefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_field_value',
            },
        ),
        migrations.CreateModel(
            name='ProductFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('field_source', models.CharField(choices=[('CORE', 'CORE'), ('DYNAMIC', 'DYNAMIC'), ('COMPUTED', 'COMPUTED')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=512)),
                ('section', models.CharField(default='Genel Bilgiler', max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_form_config',
                'ordering': ['section', 'order', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='ProductListColumnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('field_source', models.CharField(choices=[('CORE', 'CORE'), ('DYNAMIC', 'DYNAMIC'), ('COMPUTED', 'COMPUTED')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_sortable', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('width', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_list_column_config',
                'ordering': ['order', 'field_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('tenant', 'barcode'), name='product_unique_tenant_barcode_nonempty'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='productdetailconfig',
            unique_together={('tenant', 'field_key', 'field_source')},
        ),
        migrations.AlterUniqueTogether(
            name='productfielddefinition',
            unique_together={('tenant', 'key')},
        ),
        migrations.AddIndex(
            model_name='productfieldvalue',
            index=models.Index(fields=['tenant', 'product'], name='product_fie_tenant__28c261_idx'),
        ),
        migrations.AddIndex(
            model_name='productfieldvalue',
            index=models.Index(fields=['tenant', 'field_definition'], name='product_fie_tenant__769dfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productfieldvalue',
            unique_together={('tenant', 'product', 'field_definition')},
        ),
        migrations.AlterUniqueTogether(
            name='productformconfig',
            unique_together={('tenant', 'field_key', 'field_source')},
        ),
        migrations.AlterUniqueTogether(
            name='productlistcolumnconfig',
            unique_together={('tenant', 'field_key', 'field_source')},
        ),
    ]
