# Generated by Django 5.2.15 on 2026-07-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('provider_key', models.CharField(max_length=32)),
                ('environment', models.CharField(choices=[('test', 'Test / Sandbox'), ('prod', 'Canlı')], default='test', max_length=8)),
                ('signing_mode', models.CharField(choices=[('client_xades', 'İmza bizde (XAdES)'), ('provider_seal', 'İmza entegratörde (mali mühür)')], default='client_xades', max_length=16)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('untested', 'Test edilmedi'), ('ok', 'Bağlantı başarılı'), ('error', 'Bağlantı hatası')], default='untested', max_length=16)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integration_connection',
                'ordering': ['provider_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_family', models.CharField(choices=[('efatura', 'e-Fatura'), ('earsiv', 'e-Arşiv'), ('erecete', 'e-Reçete')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='signing.integrationconnection')),
            ],
            options={
                'db_table': 'document_routing',
            },
        ),
        migrations.CreateModel(
            name='SignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('erecete', 'e-Reçete'), ('earsiv', 'e-Arşiv'), ('efatura', 'e-Fatura')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('signed', 'Signed'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('data_to_sign', models.TextField(blank=True, help_text='Base64-encoded payload bytes')),
                ('algorithm', models.CharField(default='SHA256_RSA_PKCS', max_length=64)),
                ('signature', models.TextField(blank=True, help_text='Base64-encoded signature')),
                ('certificate_der', models.TextField(blank=True, help_text='Base64-encoded signer certificate DER')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('signed_document', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_tasks', to='contenttypes.contenttype')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sign_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSigningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_vkn', models.CharField(blank=True, max_length=11)),
                ('supplier_title', models.CharField(blank=True, max_length=255)),
                ('supplier_tax_office', models.CharField(blank=True, max_length=128)),
                ('supplier_city', models.CharField(blank=True, max_length=128)),
                ('supplier_district', models.CharField(blank=True, max_length=128)),
                ('supplier_street', models.CharField(blank=True, max_length=255)),
                ('supplier_country', models.CharField(default='Türkiye', max_length=64)),
                ('certificate_type', models.CharField(choices=[('mali_muhur', 'Mali Mühür (kurumsal)'), ('personal', 'Kişisel e-imza')], default='personal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signing_profile', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_signing_profile',
            },
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['tenant', 'provider_key'], name='integration_tenant__32ece8_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrouting',
            constraint=models.UniqueConstraint(fields=('tenant', 'document_family'), name='uniq_routing_per_family'),
        ),
        migrations.AddIndex(
            model_name='signtask',
            index=models.Index(fields=['tenant', 'document_type', 'status'], name='sign_task_tenant__6810ff_idx'),
        ),
        migrations.AddIndex(
            model_name='signtask',
            index=models.Index(fields=['tenant', 'content_type', 'object_id'], name='sign_task_tenant__106dc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='signtask',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('tenant', 'content_type', 'object_id', 'document_type'), name='uniq_sign_task_source_per_type'),
        ),
    ]
