# Generated by Django 5.2.14 on 2026-06-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('erecete', 'e-Reçete'), ('earsiv', 'e-Arşiv'), ('efatura', 'e-Fatura')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('signed', 'Signed'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('data_to_sign', models.TextField(blank=True, help_text='Base64-encoded payload bytes')),
                ('algorithm', models.CharField(default='SHA256_RSA_PKCS', max_length=64)),
                ('signature', models.TextField(blank=True, help_text='Base64-encoded signature')),
                ('certificate_der', models.TextField(blank=True, help_text='Base64-encoded signer certificate DER')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_tasks', to='contenttypes.contenttype')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sign_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'document_type', 'status'], name='sign_task_tenant__6810ff_idx'), models.Index(fields=['tenant', 'content_type', 'object_id'], name='sign_task_tenant__106dc6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('tenant', 'content_type', 'object_id', 'document_type'), name='uniq_sign_task_source_per_type')],
            },
        ),
    ]
