# Generated by Django 5.2.14 on 2026-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_seed_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='signtask',
            name='provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='signtask',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='signtask',
            name='provider_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signtask',
            name='signed_document',
            field=models.TextField(blank=True),
        ),
    ]
