# Generated by Django 5.2.14 on 2026-06-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0003_signtask_provider_signtask_provider_payload_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('provider_key', models.CharField(max_length=32)),
                ('environment', models.CharField(choices=[('test', 'Test / Sandbox'), ('prod', 'Canlı')], default='test', max_length=8)),
                ('signing_mode', models.CharField(choices=[('client_xades', 'İmza bizde (XAdES)'), ('provider_seal', 'İmza entegratörde (mali mühür)')], default='client_xades', max_length=16)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('untested', 'Test edilmedi'), ('ok', 'Bağlantı başarılı'), ('error', 'Bağlantı hatası')], default='untested', max_length=16)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integration_connection',
                'ordering': ['provider_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_family', models.CharField(choices=[('efatura', 'e-Fatura'), ('earsiv', 'e-Arşiv'), ('erecete', 'e-Reçete')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.tenant')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='signing.integrationconnection')),
            ],
            options={
                'db_table': 'document_routing',
            },
        ),
        migrations.CreateModel(
            name='TenantSigningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_vkn', models.CharField(blank=True, max_length=11)),
                ('supplier_title', models.CharField(blank=True, max_length=255)),
                ('supplier_tax_office', models.CharField(blank=True, max_length=128)),
                ('supplier_city', models.CharField(blank=True, max_length=128)),
                ('supplier_district', models.CharField(blank=True, max_length=128)),
                ('supplier_street', models.CharField(blank=True, max_length=255)),
                ('supplier_country', models.CharField(default='Türkiye', max_length=64)),
                ('certificate_type', models.CharField(choices=[('mali_muhur', 'Mali Mühür (kurumsal)'), ('personal', 'Kişisel e-imza')], default='personal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signing_profile', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_signing_profile',
            },
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['tenant', 'provider_key'], name='integration_tenant__32ece8_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrouting',
            constraint=models.UniqueConstraint(fields=('tenant', 'document_family'), name='uniq_routing_per_family'),
        ),
    ]
